### ISSUE TITLE
如果客户端不使用依赖注入框架，可以实现吗？比如现有的一个winForm老项目做为客户端

### ISSUE THREAD

**Issue by hrx521** [AchievedOwner/Bizer#14]
请问，如果客户端不使用依赖注入框架，可以实现吗？比如现有的一个winForm老项目做为客户端

**Comment by teacher-zhou** [comment]
技术来说有点费劲，其实 winform 也可以做到依赖注入，而且很容易

**Comment by hrx521** [comment]
感谢回复。下来我研究研究，我还得考量一下，为旧项目引入依赖注入库的代价。

**Comment by teacher-zhou** [comment]
> 感谢回复。下来我研究研究，我还得考量一下，为旧项目引入依赖注入库的代价。

我这边考虑一下对 framework 旧版本的兼容，最次也得是4.6.1以上了
