### ISSUE TITLE
前端是纯HTML+JS如何使用

### ISSUE THREAD

**Issue by bineran** [AchievedOwner/Bizer#16]
前端是纯HTML+JS如何使用，不是.NET的前端框架要如何来使用呢

**Comment by teacher-zhou** [comment]
> 前端是纯HTML+JS如何使用，不是.NET的前端框架要如何来使用呢

臣妾做不到呀，毕竟这是基于 .NET 框架的
纯JS的，你可以考虑使用 JQuery，这就是基于 js 的库，来给后端发送 http 请求
